#!/bin/bash

yellow='\e[1;33m'
green='\e[1;32m'

DO1G='/var/www/owncloud/./1G'
DO2G='/var/www/owncloud/./2G'
DO5G='/var/www/owncloud/./5G'
DO10G='/var/www/owncloud/./10G'
DO50G='/var/www/owncloud/./50G'


clear
echo -e "${green}"
echo "1.1G (Go Easy)"
echo "2.2G (For those that can't be without thier files!)"
echo "3.5G (Now your getting there)" 
echo "4.10G (Do it like a MAN, GO HARD!)"
echo "5.50G (You Crazy!)" 
#Guided install
echo -e "${yellow}"
while true;do
    read -p "Please select your install method: " abc
    case $abc in
         [1] ) "${DO1G}"; tput sgr0; break;;
         [2] ) "${DO2G}"; tput sgr0; break;;
         [3] ) "${DO5G}"; tput sgr0; break;;
         [4] ) "${DO10G}"; tput sgr0; break;;
         [5] ) "${DO50G}"; tput sgr0; break;;
         [EeQq]* ) echo "Thank You For Trying this out!!"; tput sgr0; exit;;
         * ) echo -e "${red}"; echo "Please Select one of the options or Exit to quit"; echo -e "${yellow}";;
 esac
done
